### ISSUE TITLE
Compile the original AAF project

### ISSUE THREAD

**Issue by MartinDelille** [markreidvfx/pyaaf#50]
This would be nice to be able to compile the AAF project.

I tried without success: https://pastebin.com/g0N5sjGx

**Comment by MartinDelille** [comment]
I found a github clone here: https://github.com/nevali/aaf

**Comment by markreidvfx** [comment]
The AAF SDK sadly hasn't been updated in about 10 years. You are probably having trouble because your version of macosx no longer has gcc. When I do full releases I use snow leopard for my own sanity.  You can use prebult libraries on the lastest version of macosx. 

This is one of the reasons I made [pyaaf2](https://github.com/markreidvfx/pyaaf2) it is pure python, has no dependencies and doesn't use the SDK at all.

**Comment by MartinDelille** [comment]
Ok [pyaaf2](https://github.com/markreidvfx/pyaaf2) is a great news I nevered heard about! What is the library status?

**Comment by markreidvfx** [comment]
It does everything the readme says ;) feel free to report any issues your encounter!
